Move data for test to `testdata`
common-workflow-language/cwl-upgrader pull request #82
Opened 2021-11-12 10:54 UTC by tom-tan

The new directory structure is as follows: `testdata/$cwlVersion/filename.cwl`.
It makes easier to distinguish CWLVersion for each file and also makes easier to make tests that depend on directory structure as discussed in #78.

2021-11-12 10:56 UTC, mr-c requested changes
Thanks! Please update `MANIFEST.in` to notice these new directories so that the release test passes

2021-11-12 11:03 UTC, tom-tan commented
Done!

2021-11-12 11:24 UTC, mr-c approved these changes

2021-11-14 10:27 UTC, merged

2021-11-14 10:27 UTC, mr-c commented
Thank you @tom-tan !