Fix tests for upgrade_document
common-workflow-language/cwl-upgrader pull request #85
Opened 2021-11-15 03:12 UTC by tom-tan

This request fixes tests that were added by #79 (introduced by me :-( ).
They should check the upgraded document and the expected document but they do not in the current implementation.

I also change `_v1_0_to_v1_1` to add `LoadListingRequirement` and `NetworkAccess` to `requirements` rather than `hints` not to break the behavior of given CWL documents. See  [listing_deep1.cwl](https://github.com/common-workflow-language/cwl-upgrader/blob/main/testdata/v1.0/listing_deep1.cwl) for example.

2021-11-15 09:07 UTC, mr-c commented
> This request fixes tests that were added by #79 (introduced by me :-( ). They should check the upgraded document and the expected document but they do not in the current implementation.

👍👍


> I also change `_v1_0_to_v1_1` to add `LoadListingRequirement` and `NetworkAccess` to `requirements` rather than `hints` not to break the behavior of given CWL documents. See [listing_deep1.cwl](https://github.com/common-workflow-language/cwl-upgrader/blob/main/testdata/v1.0/listing_deep1.cwl) for example.

Interesting. This does not match the behavior of the reference runner. https://github.com/common-workflow-language/cwltool/blob/352daf6d53f12df4cd960c0343ef659924aa9712/cwltool/update.py#L127

@tetron Do you remember why we put these as hints instead of requirements?

2021-11-15 09:25 UTC, mr-c requested changes
A couple lines without test coverage.

2021-11-15 09:25 UTC, mr-c commented on cwlupgrader/main.py
> +                    reqs.append(
Needs a test

2021-11-15 09:25 UTC, mr-c commented on cwlupgrader/main.py
> +                document["requirements"] = reqs
Needs a test

2021-11-15 11:58 UTC, tom-tan commented on cwlupgrader/main.py
> +                    reqs.append({"class": "NetworkAccess", "networkAccess": True})
Added!

2021-11-15 13:17 UTC, mr-c commented on cwlupgrader/main.py
> +                    reqs.append({"class": "NetworkAccess", "networkAccess": True})
Ah, but it still show as not having test coverage at https://github.com/common-workflow-language/cwl-upgrader/pull/85/files#diff-8b00c89aa5e22637a7d8faef653e434ac242b1fda440d6b0422c73197f2e39a4L373 ..

2021-11-16 15:48 UTC, tom-tan commented
ping!

2021-11-16 16:00 UTC, mr-c reviewed
LGTM, but @tetron needs to share his opinion about adding `LoadListingRequirement` and `NetworkAccess` to reqs instead of hints when upgrading v1.0 → v1.1

2021-11-16 16:02 UTC, mr-c approved these changes

2021-11-16 16:02 UTC, merged

2021-11-16 16:02 UTC, mr-c commented
@tom-tan , Peter says "sure" :-)

https://matrix.to/#/!RQMxrGNGkeDmWHOaEs:gitter.im/$2uVLM10OOgig25VMO8ZY2kAEQaiI05nYKW1ijblsC2Y